dstackai/gpuhunt

.github/workflows/release.yml
.github/workflows/test.yml
pyproject.toml
src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/models.py
src/gpuhunt/providers/tensordock.py
src/tests/_internal/test_constraints.py
src/tests/providers/test_tensordock.py

* Make GPU names case-insensitive
* Use country as a location
* Cap CPU/RAM/storage if not all GPUs are taken

TensorDock fixes

---

.github/workflows/catalogs.yml
README.md
pyproject.toml
requirements.txt
src/gpuhunt/__main__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/providers/nebius.py
src/integrity_tests/test_nebius.py

* Support GPU and CPU platforms in eu-north1-c region
* Include Nebius in the static catalog

Add Nebius provider

---

src/gpuhunt/providers/nebius.py
src/tests/providers/test_providers.py

add tests for providers

---

README.md
src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/storage.py
src/gpuhunt/providers/aws.py
src/gpuhunt/providers/azure.py
src/gpuhunt/providers/gcp.py
src/gpuhunt/providers/lambdalabs.py
src/gpuhunt/providers/nebius.py
src/gpuhunt/providers/tensordock.py
src/gpuhunt/providers/vastai.py
src/tests/_internal/test_catalog.py

Closes #12 
* Provider now returns sorted offers list
* Query preserve this order doing merge

Preserve providers' offers order

---

.github/workflows/catalogs.yml
.pre-commit-config.yaml
README.md
pyconfig.toml
pyproject.toml
requirements_dev.txt
src/gpuhunt/__main__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/models.py
src/gpuhunt/providers/datacrunch.py
src/integrity_tests/test_datacrunch.py
src/tests/providers/test_datacrunch.py

Add DataCrunch provider

---

src/gpuhunt/providers/datacrunch.py
src/integrity_tests/test_datacrunch.py
src/tests/providers/test_datacrunch.py

I've reworked test `test_gpu_present`.

Fix DataCrunch catalog

---

src/gpuhunt/providers/nebius.py

Hardcode Nebius platforms

---

pyproject.toml
src/gpuhunt/providers/datacrunch.py
src/tests/providers/test_datacrunch.py

Fix gpu_memory calculation

---

src/gpuhunt/_internal/catalog.py
src/tests/_internal/test_catalog.py

Remove not loaded providers from default list

---

src/gpuhunt/providers/datacrunch.py
src/tests/providers/test_datacrunch.py

Sort DataCrunch offers by price

---

src/gpuhunt/providers/tensordock.py
src/gpuhunt/providers/vastai.py
src/tests/providers/test_vastai.py

Normalize VastAI GPU memory

---

src/gpuhunt/__init__.py

Export KNOWN_GPUS

---

.github/workflows/catalogs.yml
src/gpuhunt/providers/aws.py
src/integrity_tests/test_all.py

* Filter out AWS Capacity Blocks (8*A100) with $0.0 price
* Add integrity test for $0.0 price
* Upgrade actions to Node 20

Fix AWS $0.0 offers

---

.pre-commit-config.yaml
src/gpuhunt/providers/azure.py
src/gpuhunt/providers/cudo.py
src/gpuhunt/providers/datacrunch.py
src/gpuhunt/providers/lambdalabs.py
src/integrity_tests/test_datacrunch.py
src/tests/providers/test_datacrunch.py

Fix incorect state in the RawCatalogItem

---

.pre-commit-config.yaml
src/gpuhunt/providers/cudo.py
src/integrity_tests/test_cudo.py

Remove "se-smedjebacken-1" from cudo locations

---

.github/workflows/catalogs.yml
README.md
src/gpuhunt/__main__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/providers/runpod.py
src/integrity_tests/test_runpod.py

Add runpod provider

---

src/gpuhunt/providers/runpod.py

[runpod] Hide A100

---

src/gpuhunt/providers/vastai.py

Return min_disk_size for vastai offers

---

.github/workflows/catalogs.yml
src/gpuhunt/_internal/catalog.py

Run catalogs workflow every hour

---

src/gpuhunt/providers/gcp.py

https://github.com/dstackai/dstack/issues/1355
See commit messages. Probably easier to review per-commit

Include local SSD in GCP pricing

---

src/gpuhunt/providers/aws.py
src/integrity_tests/test_aws.py

https://github.com/dstackai/dstack/issues/1235

Add AWS L4 offers in catalog

---

src/gpuhunt/providers/vastai.py

Fixes: https://github.com/dstackai/gpuhunt/issues/83

vastai: don't fail if cpu_cores = null or 0

---

src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/models.py
src/gpuhunt/_internal/utils.py
src/gpuhunt/providers/gcp.py
src/tests/_internal/test_models.py

Closes: https://github.com/dstackai/gpuhunt/issues/87

gcp: remove `tpu-` prefix, set vendor

---

src/gpuhunt/_internal/models.py

Fixes: https://github.com/dstackai/gpuhunt/issues/89

Make gpu_vendor optional

---

src/gpuhunt/providers/aws.py

The way AWS reports the VRAM size for L4 is
inconsistent with other GPUs. The reported size is 24 base-10 gigabytes, while L4 is actually 24
base-2 gibibytes, same as many other NVIDIA GPUs.
Additionally, for multi-unit L4 instances AWS
reports the total VRAM size instead of the size of a single unit.
This commit hardcodes the correct L4 VRAM size
until there are changes from AWS' end.
Part of #91

Hardcode VRAM size for AWS L4

---

src/gpuhunt/providers/lambdalabs.py

This PR updates the [Lambda Cloud regions](https://docs.lambdalabs.com/on-demand-cloud/overview#regions).

Update the Lambda Cloud regions

---

src/integrity_tests/test_azure.py

Fixes failing Integrity tests.

Add newzealandnorth azure location to tests

---

src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/models.py
src/gpuhunt/providers/runpod.py
src/tests/_internal/test_models.py

Hey there!
I have added some AMD accelerators to this package.
While I added architecture, it is not yet exposed in the CatalogItem, I think we can add that as well (and add them for Nvidia as well) so these can be pinned?
Let me know.

Expand AMD accelerators.

---

src/gpuhunt/providers/aws.py
src/integrity_tests/test_aws.py

feature(aws): Add p5e and g6e instances

---

src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/providers/gcp.py
src/gpuhunt/resources/tpu_pricing.json

This PR adds proper support for TPU v6e. Previously, the v6e instances were included in the catalog but with wrong prices.
The PR also introduces "GPUHUNT_CATALOG_DIR" env var that allows using a local catalog for development purposes.

Support TPU v6e

---

src/gpuhunt/_internal/constraints.py
src/gpuhunt/providers/gcp.py

The PR adds real CPU, RAM, and GPU memory values for TPU offers (only for one host TPUs).

Add TPU hardware resources

---

src/gpuhunt/providers/gcp.py
src/gpuhunt/resources/tpu_pricing.json

The PR adds spot prices for TPU v6e and updates spot prices for older TPUs.

Update spot TPUs prices

---

.github/workflows/catalogs.yml
.github/workflows/test.yml
README.md
pyproject.toml
src/gpuhunt/__main__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/providers/nebius.py
src/integrity_tests/test_nebius.py
src/tests/providers/test_providers.py

Part of https://github.com/dstackai/dstack/issues/2390
Sample catalog: https://dstack-gpu-pricing.s3.eu-west-1.amazonaws.com/stgn/v2/20250331-7375/catalog.zip

Add Nebius catalog

---

src/gpuhunt/providers/lambdalabs.py
src/integrity_tests/test_lambdalabs.py

https://github.com/dstackai/dstack/issues/2476

Fetch Lambda regions instead of hardcoding

---

.github/workflows/catalogs.yml
src/gpuhunt/providers/cudo.py
src/gpuhunt/providers/datacrunch.py

See https://github.com/dstackai/dstack/issues/2486
Also fixes balancing logic to include H100 offers.

Update Cudo GPU list

---

src/gpuhunt/providers/gcp.py

There was an error setting runtime variables that are not used anywhere. Remove such variables. Also prevent local variables of one loop iteration from leaking to other loop iterations if the TPU type is unknown.

Fix collecting GCP catalog

---

README.md
src/gpuhunt/__init__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/models.py
src/tests/_internal/test_models.py

Part-of: https://github.com/dstackai/dstack/issues/2101

Add CPU architecture filter

---

src/gpuhunt/providers/vastai.py
src/tests/providers/test_vastai.py

Pass `gpu_name` and `gpu_ram` to filter
Closes #142

[Bug] Several issues with `vastai` provider #142

---

src/gpuhunt/_internal/catalog.py
src/gpuhunt/providers/azure.py

Addresses https://github.com/dstackai/dstack/issues/2632

Support Azure Fsv2-series

---

src/gpuhunt/providers/runpod.py

[RunPod] B200 is not included into the offers 

---

README.md
src/gpuhunt/providers/cloudrift.py
src/integrity_tests/test_cloudrift.py

Test was failing when one of hardcoded gpus couldn't be found on the list of available gpus.
Fixes #160

Fixed gpu_present test
