dstackai/gpuhunt

src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/default.py
src/gpuhunt/_internal/models.py
src/gpuhunt/providers/vastai.py
src/tests/_internal/test_constraints.py

* Filter VastAI offers during search

Improve VastAI provider

---

src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/models.py
src/gpuhunt/providers/aws.py
src/gpuhunt/providers/azure.py
src/gpuhunt/providers/datacrunch.py
src/gpuhunt/providers/gcp.py
src/gpuhunt/providers/lambdalabs.py
src/gpuhunt/providers/nebius.py
src/gpuhunt/providers/tensordock.py
src/gpuhunt/providers/vastai.py
src/tests/_internal/test_catalog.py
src/tests/_internal/test_constraints.py
src/tests/providers/test_datacrunch.py
src/tests/providers/test_tensordock.py

Initial support for disk size.
Now `CatalogItem` has `disk_size` (optional).  If not set, the disk size is not pre-defined and can be specified when an instance is created.
Limitations:
- If `disk_size` is not set, the `price` doesn't include the disk price.

Support disk size

---

.github/workflows/catalogs.yml
src/gpuhunt/providers/azure.py
src/integrity_tests/test_all.py

Issue 45 failed srcintegrity teststest allpytestallcatalogstest non zero cost

---

README.md
src/gpuhunt/providers/cudo.py

Fix #52 
Example:
```
❯ python test_case.py
QueryFilter(provider=['cudo']) 2695
QueryFilter(provider=['cudo'], min_gpu_count=0) 2237
QueryFilter(provider=['cudo'], min_gpu_count=0, max_gpu_count=0) 2237
QueryFilter(provider=['cudo'], min_gpu_count=0, max_gpu_count=1) 2266
QueryFilter(provider=['cudo'], min_gpu_count=1, max_gpu_count=1) 29
```

[cudo] improve the filtering of offers

---

.github/workflows/catalogs.yml
README.md
pyproject.toml
src/gpuhunt/__main__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/utils.py
src/gpuhunt/providers/oci.py
src/integrity_tests/test_oci.py
src/tests/_internal/test_utils.py
src/tests/providers/test_oci.py

This PR adds support for Oracle Cloud Infrastructure in gpuhunt. This is part of the OCI backend implementation for dstack, see https://github.com/dstackai/dstack/issues/1194

Add OCI instances catalog

---

src/gpuhunt/providers/runpod.py

The fix solves the mismatch in offer prices between dstack's Runpod offers and Runpod's web portal. This happened due to logical issue while converting offers to `RawCatalogItem.`

Fix Runpod Spot Offer Mismatch

---

src/gpuhunt/providers/oci.py
src/integrity_tests/test_oci.py

This commit adds support for new instances in the OCI catalog: all BM.GPU instances, several BM.Standard instances, all BM.HPC and BM.Optimized instances.
VM.DenseIO instances are dropped from the catalog, since they are not used in dstack and their bare metal versions have slightly more sophisticated pricing that we don't need to support otherwise.
https://github.com/dstackai/dstack/issues/1194

Add OCI Bare Metal instances in catalog

---

pyproject.toml
src/gpuhunt/providers/gcp.py
src/gpuhunt/resources/tpu_pricing.json
src/integrity_tests/test_gcp.py

1. The TPU offering has been added **on top** of the existing implementation. Please review the changes and provide any feedback or suggestions.
2. I have introduced a new **resources** folder to the project structure. The resources folder contains a file named **tpu_pricing.json**, which includes TPU pricing information sourced from the [GCP Pricing](https://cloud.google.com/tpu/pricing)
-    **Purpose of tpu_pricing.json**
The tpu_pricing.json file serves as a fallback mechanism for fetching TPU pricing information. The pricing implementation is designed to first attempt fetching prices directly from the GCP API. If the price information is not available through the API, the implementation will then fetch the pricing details from the tpu_pricing.json file.
Here are the TPU series with …

Add TPU support in GCP

---

src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/utils.py

TPUs does not specify **cpu** and **memory** hence different constraint matching is added.

Add minimum constraints for TPU

---

src/gpuhunt/providers/gcp.py
src/integrity_tests/test_gcp.py

This adds two instance types: a3-highgpu-8g and a3-megagpu-8g. Both on-demand and spot versions.
https://github.com/dstackai/dstack/issues/1240

Add H100 GPU in GCP catalog

---

src/gpuhunt/providers/aws.py
src/integrity_tests/test_aws.py

This adds on-demand and spot p5.48xlarge instances. Part of https://github.com/dstackai/dstack/issues/1238

Add H100 GPU in AWS catalog

---

src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/models.py
src/gpuhunt/providers/cudo.py
src/gpuhunt/providers/tensordock.py
src/tests/_internal/test_catalog.py
src/tests/_internal/test_constraints.py

Previously, the values in `QueryFilter.gpu_name`
and `QueryFilter.provider` were assumed to always
be lowercase. However, it was not enforced when
`QueryFilter` was constructed by setting
attributes directly, e.g.
`query_filter.gpu_name = ["A10"]`, or adding
new values to the list, e.g.
`query_filter.gpu_name.append("A10")`. This lead
to incorrect filtering.
Now `QueryFilter.gpu_name` and
`QueryFilter.provider` can have mixed-case values
and it is the responsibility of the reader to
convert them to lowercase for comparisons.
https://github.com/dstackai/dstack/issues/1352

Fix filter with uppercase GPU or provider name

---

src/gpuhunt/__init__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/providers/vastai.py
src/tests/_internal/test_constraints.py
src/tests/providers/test_vastai.py

The `correct_gpu_memory` method is based on
vastai's `normalize_gpu_memory` but only uses the
known GPU memory if it differs from reported
memory by no more than 7%. This allows to avoid
unintended corrections for vGPUs. The method is
made public so that it can be used in `dstack`.
Part of https://github.com/dstackai/dstack/issues/1523

Add public method for GPU memory approximation

---

src/gpuhunt/providers/runpod.py

Currently, `dstack` can only provision Secure
Cloud offers, so it's safe to remove Community
Cloud.
Fixes https://github.com/dstackai/dstack/issues/1886

Remove RunPod Community Cloud offers from catalog

---

src/gpuhunt/providers/gcp.py

Removes a pydantic import introduced in #112 since gpuhunt does not have pydantic as a dependency.

Replace pydantic model with dataclass

---

src/gpuhunt/providers/runpod.py

Issue: 
Runpod's API did not return Mi300x although it was available on Runpod's web console.
Solution:
Before the API would return Mi300x instances in secure cloud with `"secureCloud": null `in the API. Now Mi300x instances of secure cloud is only returned with `"secureCloud": true`. 
Also, we were only using secure cloud instances, therefore "secureCloud": true will not have effect on our offer list.

Fix Runpod Secure Cloud API

---

.github/workflows/catalogs.yml
src/gpuhunt/__main__.py
src/gpuhunt/_internal/catalog.py
src/gpuhunt/_internal/constraints.py
src/gpuhunt/_internal/models.py
src/gpuhunt/_internal/storage.py
src/gpuhunt/_internal/utils.py
src/gpuhunt/providers/oci.py
src/gpuhunt/scripts/catalog_v1/__main__.py
src/integrity_tests/test_oci.py
src/tests/_internal/test_constraints.py
src/tests/_internal/test_models.py
src/tests/scripts/test_catalog_v1.py

- Introduce the concept of catalog item flags so that items that break compatibility are only returned when their flags are queried explicitly.
- Add OCI spot instances as an example of catalog items with flags.
- Publish new catalogs under the /v2 prefix.
- Convert /v2 catalogs to /v1 catalogs for legacy users. /v1 catalogs will not have any items with flags, as they can potentially break compatibility.
https://github.com/dstackai/dstack/issues/1375

Catalog item flags & OCI spot instances

---

src/gpuhunt/providers/runpod.py
src/integrity_tests/test_runpod.py

- Add community cloud offers to the catalog. They won't be visible to older dstack versions and won't break them even without compatibility flags, because these offers belong to an independent set of regions (country codes), while older dstack versions had a different hardcoded set of regions (datacenter IDs).
- Slightly refactor the RunPod provider to allow for this new feature and simplify the implementation.
https://github.com/dstackai/dstack/issues/1892

Support RunPod Community Cloud

---

src/gpuhunt/providers/azure.py
src/integrity_tests/test_azure.py

Not sure why, but setting `api-version` to `2023-01-01-preview` leads to unstable results with a different set of locations each time. Using the default API version fixes this.

Fix Azure integrity tests

---

.github/workflows/release.yml
.github/workflows/test.yml

Tests in the release workflow were failing because of a missing condition to skip the Nebius module on Python 3.9. Fixed by refactoring the release workflow to call the test workflow that has the up-to-date jobs for running tests.
Sample workflow run: https://github.com/dstackai/gpuhunt/actions/runs/14203797933

Fix release workflow

---

src/gpuhunt/providers/gcp.py

Sku description for spot megas is `Nvidia H100 80GB Plus GPU attached to Spot Preemptible VMs running in ____`. This adds the name mapping for it.

Fix a3 mega spot instances not being populated

---

src/gpuhunt/providers/cudo.py

Cudo renamed /vms/machine-types-2 to /vms/machine-types, which they claim are functionally equivalent.

Use /vms/machine-types cudo endpoint

---

src/integrity_tests/test_lambdalabs.py

us-east-2 is not returned in the list of images.
This may mean that the region is currently
disabled. While it is still shown in the Lambda
console, no instances are available there.

Fix Lambda integrity tests

---

src/gpuhunt/providers/nebius.py
src/integrity_tests/test_nebius.py

Plus, it adds B200 GPU for Nebius

[Nebius] Add spot instances and B200 support #165

---

src/gpuhunt/providers/gcp.py
src/integrity_tests/test_gcp.py

Add spot A4 instances with the B200 GPU. Their
pricing model is slightly different from other
instance types - the price is proportional to the
number of GPUs.
Additionally, remove any on-demand GCP offers that
are not actually available on demand, even if the
API returns on-demand prices. This drops A3 High
instances with less than 8 GPUs from the catalog.
https://github.com/dstackai/dstack/issues/3088

Add GCP A4 instances
